### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [SaltanovskaV/my_project_kinozal#1]
1)
код невалиден
![image](https://user-images.githubusercontent.com/8464662/125455571-b592f1e6-dad5-43e5-95f6-41e3c876e441.png)

2)
стиль невалиден
![image](https://user-images.githubusercontent.com/8464662/125455657-bb2a0933-0921-4013-b351-d6e2f7f509af.png)

3)
допускаются отступы только 2 или 4 пробела, но одинаково для всего проекта, включая css и js
![image](https://user-images.githubusercontent.com/8464662/125455729-a7239289-3872-45d2-8dea-c214b37dd8c6.png)

4)
при переключении нет анимации
![image](https://user-images.githubusercontent.com/8464662/125455826-31aedc13-a184-47de-ab7a-0c99397236fc.png)

5)
некорректный отступ
![image](https://user-images.githubusercontent.com/8464662/125455949-6b97c533-9bad-46e3-a9f6-e1a5ad84da08.png)

6)
некорректный отступ
![image](https://user-images.githubusercontent.com/8464662/125456024-7b027a65-21dd-4b98-8821-b9c59516b06d.png)

**Comment by SaltanovskaV** [comment]
https://github.com/SaltanovskaV/my_project_kinozal
https://saltanovskav.github.io/my_project_kinozal/

**Comment by Alecto** [comment]
4 - не выполнено

**Comment by SaltanovskaV** [comment]
исправила
https://github.com/SaltanovskaV/my_project_kinozal/issues
https://saltanovskav.github.io/my_project_kinozal/

**Comment by Alecto** [comment]
правильно, работа принята.
Валерія Салтановська, правильно?

ср, 14 июл. 2021 г. в 13:00, SaltanovskaV ***@***.***>:

**Comment by SaltanovskaV** [comment]
да, все верно)) на укр.языке
